### ISSUE TITLE
Partybuff random icon sizes

### ISSUE THREAD

**Issue by Mercurian** [KenshiDRK/Addons#2]
So how come half the icons are "10" and some are double that.

I changed the settings from "10" to "20" and now some are randomly double those. Usually shell protect and blink, but not limited to those.

**Comment by KenshiDRK** [comment]
could you link me a screenshot pls?

**Comment by Mercurian** [comment]
I mean I can, but do I really need to? I literally described in explicit detail the issue, seeing it doesn't show anything I didn't just say...

Image; party member 2-6 have randomly enlarged icons (double sized)

**Comment by Mercurian** [comment]
https://ibb.co/hQ8jcF

JESUS FUCKING CHRIST EVERY SITE GIVES A GOD DAMN ERROR UPLOADING THE FUCKING PICTURE!
There.

It seems to be Icons 1 and 3 

Verified, it is Icons 1 and 3 are double sized;

**Comment by Mercurian** [comment]
https://ibb.co/fHJpBa

**Comment by Mercurian** [comment]
I believe I already fixed it by editing your lua.

You have a "or" statement, I changed that shit to straight up say 10, no or. Looks good now.

**Comment by KenshiDRK** [comment]
thats weird, is the first time I see it. The or statement shouldn't be the problem, it's there to protect it for ppl changing the settings manually and adding a different size from 20 and 10. The only I can think off it is not changing the size sometimes and then it uses the size of the png file that is 32x32.

**Comment by KenshiDRK** [comment]
I think I found the problem, if you are on live version of windower the problem might be the images.lua library, I had problems with resizing and some changes needed to be made on the images library, but the images.lua on dev version is still not on live version. I guess I added the resizing feature too early, you can fix it by downloading the images library here.
https://github.com/Windower/Lua/blob/dev/addons/libs/images.lua
right click on raw button and save link as to download it, then put in inside the addons/libs folder.

**Comment by KenshiDRK** [comment]
The fixes on the images library are already live so this issue should be fixed.
